<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <WarningLevel>3</WarningLevel>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>FASTSERIALIZATION_PUBLIC;STREAMREADER_PUBLIC</DefineConstants>
  </PropertyGroup>

</Project>
