////////////////////////////////////////////////////////////////////////////////
// Module: V6ClrEventVersions.cs
//
// Notes:
// Recovers the event VERSION for CLR runtime events read out of a v6 capture.
//
// Why this is needed at all: v6 made nearly every metadata property optional
// (NetTraceFormat.md, "Most of the metadata fields are now optional"), and
// `dotnet-trace collect-linux` takes that all the way. On a real 764MB
// reference capture every one of the 33 Microsoft-Windows-DotNETRuntime
// metadata rows carries a ProviderGuid and NOTHING else - no Version, no
// Level, no Keywords, and an empty FieldDescriptions list. That is legal, and
// it follows from how these events reach the file: the runtime emits them
// through the Linux user_events mechanism as opaque payload blobs, so the
// writer knows the event's numeric id but has no manifest to describe it
// with. (It says so, too - it tags those events with a label `Error` =
// "Expected actual values"; see V6LabelListTable.)
//
// This project's CLR decoders are version-gated, so a Version of 0 is not a
// harmless default - it is silently wrong output:
//
//   - ExceptionEventProjector skips any event with Version < 1, which would
//     have discarded all 72,674 exceptions in the reference capture.
//   - AllocationEventProjector skips GCAllocationTick with Version < 2.
//   - ClrGcEnd and ClrGcSuspendEEBegin read a field as int32 at Version >= 1
//     and int16 below it, so the wrong version does not fail, it returns a
//     plausible wrong number.
//
// The order of authority is: an explicit Version label on the event (v6 lets
// a LabelList override metadata, and the reference capture really does use
// this - its GCPerHeapHistory events carry Version = 3 that way), then the
// metadata row's own Version if it declared one, then this file.
//
// WHERE THE TABLE COMES FROM: a v5 capture's metadata carries both the event
// id AND the version the runtime emitted it at, so v5 captures ARE the
// authoritative source for what a given CLR event id's version is - no
// guessing required, and no dependency on TraceEvent. EmittedVersionFor below
// was generated by running this tool's own plain mode (see Program.cs's
// "== Event schemas ==" section, which exists for this) over four real v5
// captures and taking the union; all four agreed on every id they shared.
// Reporting the same version v5 reports also keeps the two paths comparable,
// which matters because the ground-truth diff tests compare projector output
// and would otherwise be comparing different decodes of the same event.
//
// The payload-length ladder in ClampToPayloadLength is a DOWNGRADE guard, not
// the primary source. It exists for the four events where the version selects
// a field WIDTH rather than just adding trailing fields - the one case the
// decoders' own `version >= N && Length >= M` guards cannot catch, because
// both widths fit inside a long-enough payload. If a capture ever carries a
// shorter payload than the table's version implies, the length wins.
////////////////////////////////////////////////////////////////////////////////

namespace DotnetInsights.NetTrace.V6 {

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

using DotnetInsights.NetTrace.Contention;
using DotnetInsights.NetTrace.Exceptions;
using DotnetInsights.NetTrace.Gc;

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

public static class V6ClrEventVersions
{
    // What an id absent from the table resolves to. 0 - "nobody told us" -
    // rather than a guess, because every CLR event this project actually
    // decodes IS in the table, and inventing a version for one it does not
    // decode could only ever change how the event overview labels a row.
    public const int UnknownVersion = 0;

    // The version the runtime emits each CLR event id at. See this file's
    // header for how this was generated and why v5 captures are authoritative
    // for it.
    public static int EmittedVersionFor(int eventId)
    {
        switch (eventId)
        {
            case 1:   return 2;   // GCStart
            case 2:   return 1;   // GCEnd
            case 3:   return 1;   // GCRestartEEEnd
            case 4:   return 2;   // GCHeapStats
            case 5:   return 1;   // GCCreateSegment
            case 6:   return 1;   // GCFreeSegment
            case 7:   return 1;   // GCRestartEEBegin
            case 8:   return 1;   // GCSuspendEEEnd
            case 9:   return 1;   // GCSuspendEEBegin
            case 10:  return 4;   // GCAllocationTick
            case 11:  return 1;
            case 13:  return 1;   // GCFinalizersEnd
            case 14:  return 1;   // GCFinalizersBegin
            case 80:  return 1;   // ExceptionThrown
            case 151: return 1;
            case 152: return 2;
            case 153: return 2;
            case 154: return 1;
            case 155: return 1;
            case 156: return 1;
            case 157: return 1;
            case 203: return 2;
            case 204: return 3;   // GCPerHeapHistory
            case 205: return 4;   // GCGlobalHeapHistory

            // Everything else observed in real v5 captures reports version 0,
            // which is also what UnknownVersion resolves to, so those ids are
            // deliberately not enumerated here.
            default:
            {
                return UnknownVersion;
            }
        }
    }

    // Resolves the version for one CLR event. metadataVersion/labelVersion are
    // -1 when the capture did not supply them.
    public static int Resolve(int eventId, int payloadLength, int metadataVersion, int labelVersion)
    {
        if (labelVersion >= 0)
        {
            return labelVersion;
        }

        if (metadataVersion > 0)
        {
            return metadataVersion;
        }

        return ClampToPayloadLength(eventId, payloadLength, EmittedVersionFor(eventId));
    }

    // Lowers `version` when this event's payload is too short to actually be
    // that version. Only the events whose version selects a field WIDTH need
    // this - see the file header.
    public static int ClampToPayloadLength(int eventId, int payloadLength, int version)
    {
        switch (eventId)
        {
            case ClrGcEventIds.GCStart:
            {
                // V0 Count/Depth/Reason/Type (16) | V1 + ClrInstanceID (18)
                // | V2 + ClientSequenceNumber (26).
                if (version >= 2 && payloadLength < 26)
                {
                    version = 1;
                }

                if (version >= 1 && payloadLength < 18)
                {
                    version = 0;
                }

                return version;
            }

            case ClrGcEventIds.GCEnd:
            {
                // V0 reads Count/Depth as int16, V1 as int32 plus a trailing
                // ClrInstanceID (10 bytes total). ClrGcEnd.Decode switches
                // field width on this.
                if (version >= 1 && payloadLength < 10)
                {
                    version = 0;
                }

                return version;
            }

            case ClrGcEventIds.GCHeapStats:
            {
                if (version >= 2 && payloadLength < 110)
                {
                    version = 1;
                }

                if (version >= 1 && payloadLength <= 92)
                {
                    version = 0;
                }

                return version;
            }

            case ClrGcEventIds.GCSuspendEEBegin:
            {
                // Another width switch: Reason/Count are int16 at V0 and
                // int32 at V1 (10 bytes with ClrInstanceID).
                if (version >= 1 && payloadLength < 10)
                {
                    version = 0;
                }

                return version;
            }

            case ClrContentionEventIds.ContentionStart:
            {
                // Not present in any v5 capture available when the table above
                // was generated, so this ladder - rather than the table - is
                // what answers for it.
                if (version == UnknownVersion)
                {
                    if (payloadLength >= 30)
                    {
                        version = 2;
                    }
                    else if (payloadLength >= 3)
                    {
                        version = 1;
                    }
                }

                return version;
            }

            case ClrExceptionEventIds.ExceptionThrown:
            {
                // Variable length (three embedded UTF-16 strings), so there is
                // no ladder - but an empty payload cannot be a V1 throw.
                if (version >= 1 && payloadLength == 0)
                {
                    version = 0;
                }

                return version;
            }

            default:
            {
                return version;
            }
        }
    }
}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

} // end of namespace(DotnetInsights.NetTrace.V6)

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
